server:
  port: ${PORT:8080}
  servlet:
    context-path: financeapi

management:
  security:
    enabled: false

spring:
  application:
    name: finance-server-api
  datasource:
    url: jdbc:h2:file:./h2db/db/financeserverdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

  profiles:
    active: dev