server:
    port: 8080
    servlet:
        context-path: /financeapi

logging:
    level:
        com.viictrp.api.finance.server.api: DEBUG
        org.springboot.web: DEBUG
    file:
        logs/spring-boot-logging.log

spring:
    application:
        name: finance-server-api

    output:
        ansi:
            enabled: DETECT

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/financeserverdb
        username: postgres
        password: 515253
        driver-class-name: org.postgresql.Driver
        platform: h2

    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: finance_api_db

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL9Dialect
            jadira:
                usertype:
                    autoRegisterUserTypes: true


    h2:
        console:
            enabled: true

    profiles:
        active: local

    jackson:
        serialization:
            write-dates-as-timestamps: false
        time-zone: America/Sao_Paulo
        locale: pt_BR

finance:
    oauth2:
        client_id: 0
        client_secret: ad70a866-c3eb-432a-9073-8c6638ed76d5